version: '3.3'

services:
  postgre:
    image: postgres
    container_name: postgreSQL
    environment:
      - POSTGRES_DB=technical_test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadminLocal
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

